name = "familu-budget"
main = "worker.py"
compatibility_date = "2026-10-08"
compatibility_flags = ["python_workers", "disable_python_external_sdk"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "family-budget-db"
database_id = "b060a66f-8b86-4dee-8e10-9db1de48d2ae"

[triggers]
crons = ["0 7 * * *"]

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true
persist = true
